First batch of doc cleanups
Trepan-Debuggers/bashdb pull request #21
Opened 2024-02-14 17:11 UTC by rocky

There is still a lot of work to do. And this is going to take a bit of time. 

A suggestion is to commit this first batch and then iterate. 

A problem with large PRs that hang out for a while is that they require lots of merges or rebases to keep them in synch.

@jansorg Your thoughts?

2024-02-15 09:34 UTC, jansorg requested changes
For now, I've read half of the files. I'll continue later with the review.
The docs seem to come from zshdb. A global search/replace for `zsh`->`Bash` and `zshdb`->`bashdb` would probably remove a bunch of the things highlighted in the review.

2024-02-15 09:34 UTC, jansorg commented on command/next.sh
> +an exception occurs at this level, or we *return*, *yield* or the
I don't think there's `yield` or threads in Bash.

2024-02-15 09:34 UTC, jansorg commented on docs/commands/breakpoints/condition.rst
> +*bp_number* is a breakpoint number. *condition* is a zsh expression
`zsh expression` -> `Bash expression`

2024-02-15 09:34 UTC, jansorg commented on docs/commands/breakpoints/tbreak.rst
> +name and a colon. Files is searched for using *sys.path*, and the `.py`
I don't think `*.py` is correct in this context.

2024-02-15 09:34 UTC, jansorg commented on docs/commands/breakpoints/tbreak.rst
> +   tbreak myfile.py:45 # Break on line 45 of myfile.py
These examples seem to be for Python, not Bash.

2024-02-15 09:34 UTC, jansorg commented on docs/commands/data/display.rst
> +**display** [ *format* ] *expression*
Is bashdb really supporting `format`? According to `help display` it's not supporting it.

2024-02-15 09:34 UTC, jansorg commented on docs/commands/data/eval.rst
> +Evaluate a Zsh Expression (`eval`)
`Zsh` -> `Bash`

2024-02-15 09:34 UTC, jansorg commented on docs/commands/data/load.rst
> +Read in lines of a *zsh-script*.
`zsh-script` -> `bash-script`

2024-02-15 09:34 UTC, jansorg commented on docs/commands/data/load.rst
> +Read in a Zsh Script (`load`)
`Zsh` -> `Bash`

2024-02-15 09:34 UTC, jansorg commented on docs/commands/files/list.rst
> +List Zsh Source Code (`list`)
`Zsh` -> `Bash`

2024-02-15 09:34 UTC, jansorg commented on docs/commands/info/breakpoints.rst
> +   zshdb<4> info breakpoints
`zshdb` -> `bashdb`

2024-02-15 09:34 UTC, jansorg commented on docs/commands/info/source.rst
> +    zshdb<1> info source
`zshdb` -> `bashdb`

2024-02-15 09:34 UTC, jansorg commented on docs/commands/info/variables.rst
> +**info variables** [*property*]
I think that `-p` is missing here.

2024-02-15 09:34 UTC, jansorg commented on docs/commands/running/debug.rst
> +**debug** [*zsh-script* [*args*...]]
`zsh-script` -> `bash-script`

2024-02-15 09:34 UTC, jansorg commented on docs/commands/running/debug.rst
> +Recursively debug into *zsh-script*.
`zsh-script` -> `bash-script`

2024-02-15 09:34 UTC, jansorg commented on docs/commands/set/autoeval.rst
> +zsh commands without having to preface expressions with
`zsh` -> `bash`

2024-02-15 09:34 UTC, jansorg commented on docs/commands/set/autolist.rst
> +    -> 1 from subprocess import Popen, PIPE
This is Python code.

2024-02-15 09:34 UTC, jansorg commented on docs/commands/set/debug.rst
> +**debug** [*zsh-script* [*args*...]]
`zsh-script` -> `bash-script`

2024-02-15 09:34 UTC, jansorg commented on docs/commands/set/debug.rst
> +Recursively debug into *zsh-script*.
`zsh-script` -> `bash-script`

2024-02-15 09:35 UTC, jansorg commented
Iterating on the docs seems best to me. Reviewing a huge PR is usually hard, too.

2024-02-15 11:59 UTC, rocky commented
These changes and more are in. I haven't been able to get readthedocs to build because this is in a branch that it is currently not recognizing.

2024-02-15 12:07 UTC, rocky commented
Ok - docs are now created at https://bashdb.readthedocs.io/en/latest/

Feel free to add links to BashdbPro, but let's merge this first.

2024-02-16 15:04 UTC, jansorg approved these changes
Thanks! 
I glanced over the .rst files, but didn't check the .png/.gif files or the build setup.

2024-02-16 16:36 UTC, merged

2024-02-16 16:37 UTC, rocky commented
BTW - I haven't forgotten about the other PR's. Busy with things right now. Also, I sent email regarding possibilities for releases.